// Shapes.idl : IDL source for Shapes
//

// This file will be processed by the MIDL tool to
// produce the type library (Shapes.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(1fca7fab-d2a5-4b07-82fc-86a917d90e52),
	version(1.0),
]
library ShapesLib
{
	importlib("stdole2.tlb");
};

